### ISSUE TITLE
Pad aid2 is not connected to anything.

### ISSUE THREAD

**Issue by tyusha0** [gnfalex/YT_yt_dlp_plugin#2]
![изображение](https://github.com/gnfalex/YT_yt_dlp_plugin/assets/27030796/be387f9c-ee6b-47ac-9d10-5ef989660061)

в mpv.conf

[vot]
ytdl-raw-options-append=use-extractors=YandexTranslate,audio-multistreams,merge-output-format=mkv
lavfi-complex="[aid2][aid1]amix=weights='0.2 0.8'[ao]"

**Comment by gnfalex** [comment]
Win 8.1 + mpv v0.37.0-241-gfe0c181b + python 3.8 не воспроизводится. Возможно это какая-то временная ошибка на серверах Yandex.Translate.
Теперь в случае отсутствия перевода - raise Exception, которые mpv точно выводит.
Пожалуйста попробуйте.
PS. Есть ли возможность из mpv получить логи yt-dlp?

**Comment by tyusha0** [comment]
> Возможно это какая-то временная ошибка на серверах Yandex.Translate. 

Это явно не проблема с серверами т.к мой bash скрипт работает (со старой версией vot-cli),


`#!/bin/bash

[[ "$1" ]] && yt_video="$1" || yt_video="$(xclip -o)"
[[ "$yt_video" != "https://"* ]] && read -p "Введите URL видео: " yt_video

vot_audio=$(node index.js "$yt_video" | cut -d " " -f 6 | tr -d $'\n')
mpv "$yt_video" \
--external-file="$vot_audio" \
--lavfi-complex="[aid1]volume=0.5[vol1];[aid2]volume=3dB[vol2];[vol1][vol2]amix[ao]"`

**Comment by gnfalex** [comment]
От меня сервера иногда начинают непрерывно отдавать время ожидания 5с. В том случае. если время ожидания повторяется - плагин прерывает работу. Ранее - ничего не сообщал, теперь - будет выдавать ошибку.
Сейчас (после обновления плагина) выводит ли какую-то ошибку?

**Comment by tyusha0** [comment]
> От меня сервера иногда начинают непрерывно отдавать время ожидания 5с. В том случае. если время ожидания повторяется - плагин прерывает работу. Ранее - ничего не сообщал, теперь - будет выдавать ошибку. Сейчас (после обновления плагина) выводит ли какую-то ошибку?

Ничего не изменилось

**Comment by tyusha0** [comment]
Если использовать так, то все работает

![изображение](https://github.com/gnfalex/YT_yt_dlp_plugin/assets/27030796/de80a37a-f4cf-4cb0-b289-3fd3a0d9bb22)

собирает в матрешку

**Comment by gnfalex** [comment]
![Clipboard03](https://github.com/gnfalex/YT_yt_dlp_plugin/assets/17051055/afe40427-bc36-43c9-a6a9-6ea2dc38d85e)
[conf+log.zip](https://github.com/gnfalex/YT_yt_dlp_plugin/files/14157768/conf%2Blog.zip)
> Ничего не изменилось
У меня тоже ничего не поменялось и работает...
Из mpv.conf  уберите "audio-multistreams,merge-output-format=mkv". Они то ли неправильно вписаны, то ли еще что - но дают команду "--use-extractors YandexTranslate,audio-multistreams,merge-output-format=mkv" вместо "--use-extractors YandexTranslate --audio-multistreams --merge-output-format=mkv" . В любом случае здесь - не нужны.
Запустите у себя mpv с параметром log-file="test.log"
Что будет в логах? Мои логи - во вложении.

**Comment by tyusha0** [comment]
похоже, что проблема была в моих настройках, а именно: 
ytdl-format="bestvideo[height<=?720][fps<=?30][vcodec^=h264]+bestaudio/best" 
после апгрейда можно уже и избавиться от этого рудимента

[test.log](https://github.com/gnfalex/YT_yt_dlp_plugin/files/14157895/test.log)
